version: '3.7'

services:
  database:
    image: postgres
    container_name: finapidb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    ports:
      - 3333:3333
      - 9229:9229
    container_name: fin_api
    restart: always
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
